# This workflow will install Python dependencies, and build the app
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get update -q && sudo apt-get install
        --no-install-recommends -y xvfb python3-dev python3-gi
        python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
        intltool enchant
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade keyrings.alt
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Build wheel and Install
      run: |
        pip3 install .
    - name: Build source distribution
      run: |
        python3 setup.py sdist
    - name: Upload source distribution archive
      uses: actions/upload-artifact@v2
      with:
        name: gourmet-current
        path: dist/gourmet-0.17.5.tar.bz2
    - name: Verify internationalization
      run: |
        python3 setup.py build_i18n
    - name: Verify icons packaging
      run: |
        python3 setup.py build_icons
