# This workflow will install Python dependencies, and build the app
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get update -q && sudo apt-get install
        --no-install-recommends -y xvfb python3-dev python3-gi
        python3-gi-cairo gir1.2-gtk-3.0 libgirepository1.0-dev libcairo2-dev
        intltool enchant python3-enchant python3-gst-1.0

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install --upgrade keyrings.alt
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

    - name: Create Internationalization
      run: |
          python3 setup.py build_i18n
          find . | grep gourmet-plugin

    - name: Install
      run: |
        pip3 install .

    - name: Create wheel and source distributions
      run: |
          python3 setup.py sdist
          mv dist/gourmet-*.tar.gz dist/gourmet-${GITHUB_SHA::8}.tar.gz

          python3 setup.py bdist_wheel
          mv dist/gourmet-*-py3-none-any.whl dist/gourmet-${GITHUB_SHA::8}-py3-none-any.whl

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
          name: gourmet
          path: ./dist/gourmet-*
