name: Create Flatpak

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  flatpak:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Flatpak
      run: |
        sudo apt install flatpak flatpak-builder

    - name: Setup Flatpak
      run: |
        flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install flathub org.gnome.Platform//3.30 org.gnome.Sdk//3.40 -y

    - name: Build Flatpak
      run: |
        flatpak-builder --repo=repo --force-clean build-dir .flatpak/io.github.thinkle.Gourmet.yml

    - name: Build Bundle
      run: |
        flatpak build-bundle repo gourmet-${GITHUB_SHA::8}.flatpak io.github.thinkle.Gourmet

    - name: Upload Flatpak
      uses: actions/upload-artifact@v2
      with:
        name: gourmet.flatpak
        path: ./gourmet-*.flatpak
